matrix:
  macos:
    IMAGE_NAME: Hosted macOS
  windows:
    IMAGE_NAME: Hosted Windows 2019 with VS2019
  linux:
    IMAGE_NAME: Hosted Ubuntu 1604

pool:
  name: $(IMAGE_NAME)

steps:
  - powershell: .\install-openjdk.ps1
    displayName: Install the OpenJDK
  - powershell: .\install-tizen.ps1
    displayName: Install the Tizen SDK
