strategy:
  matrix:
    macos:
      IMAGE_NAME: Hosted macOS High Sierra
    macos2:
      IMAGE_NAME: Hosted macOS
    windows2017:
      IMAGE_NAME: Hosted VS2017
    windows2019:
      IMAGE_NAME: Hosted Windows 2019 with VS2019
    linux:
      IMAGE_NAME: Hosted Ubuntu 1604

pool:
  name: $(IMAGE_NAME)

steps:
  - powershell: .\install-openjdk.ps1
    displayName: Install the OpenJDK
  - powershell: .\install-tizen.ps1
    displayName: Install the Tizen SDK
  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      pathToPublish: '$(Agent.HomeDirectory)/.package-manager/install-log/package-manager'
      artifactName: '$(Agent.JobName)-package-manager-install-log'
