strategy:
  matrix:
    macos:
      IMAGE_NAME: Hosted macOS
    windows:
      IMAGE_NAME: Hosted VS2017
    linux:
      IMAGE_NAME: Hosted Ubuntu 1604
      
pool:
  name: $(IMAGE_NAME)

steps:
  - powershell: .\install-openjdk.ps1
    displayName: Install the OpenJDK
  - powershell: .\install-tizen.ps1
    displayName: Install the Tizen SDK
