jobs:
  - template: azure-templates-bootstrapper.yml
    parameters:
      name: native_tizen_windows
      displayName: Build Native Tizen (Windows)
      vmImage: vs2017-win2016
      target: externals-tizen
