jobs:
  - job: native_tizen_windows
    displayName: Build Native Tizen (Windows)
    pool:
      vmImage: vs2017-win2016
    steps:
      - checkout: self
        submodules: recursive
      - ${{ if startsWith('native_tizen_windows', 'native_') }}:
        # switch to Python 2.7
        - task: UsePythonVersion@0
          displayName: Switch to Python to 2.7
          inputs:
            versionSpec: '2.7'
            architecture: 'x64'
        # install android ndk
        - ${{ if contains('native_tizen_windows', '_android_') }}:
          - powershell: .\scripts\install-android-ndk.ps1
            displayName: Install the Android NDK
        # install tizen
      - ${{ if contains('native_tizen_windows', '_tizen_') }}:
        - ${{ if not(contains('vs2017-win2016', 'win')) }}:
          - powershell: .\scripts\install-tizen.ps1
            displayName: Install the Tizen SDK
        - ${{ if contains('vs2017-win2016', 'win') }}:
          - powershell: .\scripts\install-openjdk.ps1
            displayName: Install the OpenJDK
          - powershell: .\scripts\install-tizen.ps1
            displayName: Install the Tizen SDK
            env:
              JAVA_HOME: $(USERPROFILE)/openjdk/jdk-10.0.2
